# MySQL JDBC connection settings
driverClassName=com.mysql.cj.jdbc.Driver
jdbcUrl=jdbc:mysql://apt3233.id.vn:3306/shopping_web_db?serverTimezone=UTC&useSSL=false
username=apt
password=Jev1pSL1y62q

# HikariCP settings
maximumPoolSize=20
minimumIdle=5
idleTimeout=30000
connectionTimeout=30000
validationTimeout=5000
leakDetectionThreshold=2000


SECRET_KEY=b5T80rrmouqs8CeXxaohLVFnFP9DgbLWWooENPW9kzAs5T9o