# MySQL JDBC connection settings
driverClassName=com.mysql.cj.jdbc.Driver
jdbcUrl=jdbc:mysql://apt3233.id.vn:3306/shopping_web_db?serverTimezone=UTC&useSSL=false
username=apt
password=JIF9234JF3

# HikariCP settings
maximumPoolSize=20
minimumIdle=5
idleTimeout=30000
connectionTimeout=30000
validationTimeout=5000
leakDetectionThreshold=2000